name: Build and Publish Docker image

  on:
    push:
      branches: [ "main" ]
      tags: [ "v*" ]

  permissions:
    contents: read
    packages: write

  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ github.repository }}
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=sha,format=long
              type=ref,event=tag

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: docker/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
